### PR TITLE
Improve / simplify goroutine management 

### PR DESCRIPTION
**Pull request by mmetc**

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Could we an alias for this function called "mikrotik" so use can provide the company name https://mikrotik.com/
So in short just add this to the map

"mikrotik":   MicroTikFormatter,
Would help https://github.com/crowdsecurity/cs-blocklist-mirror/issues/32

**Comment by LaurenceJJones** [comment]
@williamdes is it "microtik" or "mikrotik"? as we should rename to save confusion

**Comment by williamdes** [comment]
Its https://mikrotik.com/

I maybe made a typo..?

**Review by sabban — APPROVED** [review]
lgtm

**Review by williamdes — APPROVED** [review]

**Pull request merged**
