### PR TITLE
CI improvements + multi arch binaries

### PR DESCRIPTION
**Pull request by williamdes**

### CODE REVIEW

**Comment by williamdes** [comment]
Wow, it builds since the first run :O

**Comment by mmetc** [comment]
I have not merged yet because I'm not sure it's a good idea to build tarballs for freebsd. The install scripts only work on Linux. We could do the binaries, though. Building the .pkg is a bit messy so it would be a good compromise for beta versions too. As soon as I've finished with the bouncer changes I'll get back to this

**Comment by mmetc** [comment]
@LaurenceJJones @williamdes I propose this, to use for all the go bouncers:

https://github.com/crowdsecurity/cs-blocklist-mirror/pull/35

It builds everything in 6 to 8 minutes, this is the result:

https://github.com/mmetc/cs-blocklist-mirror/releases/tag/test-2.1.1

**Comment by mmetc** [comment]
And of course thanks a lot @williamdes for your solution, I just generalized it and made it reusable

**Comment by williamdes** [comment]
> And of course thanks a lot @williamdes for your solution, I just generalized it and made it reusable

Can you re open this PR?
I will remove the multi arch changes so the CI ones can be merged?

**Comment by williamdes** [comment]
Should be okay and ready for review

**Comment by williamdes** [comment]
> linux/386

32bit machines still exist and recycling an old pc to host this firewall mirror is quite good idea 

> linux/arm/v6,linux/arm/v7

RaspberryPi and other similar boards 🎉 
I would like to add arm64 but maybe we can not for some reason, or I would have it on the list already 

> linux/ppc64le,linux/s390x

It's very vendor specific, but I have a VM at IBM running on s390x. So that would help me test at least 
We could remove support but that would not make sense as we now release built binaries for those archs 


Does it look convincing?

**Comment by mmetc** [comment]
> 32bit machines still exist and recycling an old pc to host this firewall mirror is quite good idea

Yes, and that's why we publish the tarballs, I'm just not sure how many of them run docker. I'm asking the team

> I would like to add arm64 but maybe we can not for some reason, or I would have it on the list already

Yes, we support arm64 already.

**Comment by mmetc** [comment]
Thanks again, I'll review the other bouncers as well

**Comment by williamdes** [comment]
> Thanks again, I'll review the other bouncers as well

Thank you so much, feel free to ping me on PR reviews 
Let's make the world multi arch compatible 

And know one thing: users will do forks and alternative images on docker that will rot and never be updated
They will do one shots to support their architecture
Nobody really wants that kind of crappy left overs
That's why I try to provide as much as possible so people do not do weird forks etc..

Cheers

**Pull request merged**
